"use client";
import {useRef,useState} from 'react';
import {CORNERS,FEATURE_HALF_WIDTH,FINAL_SCORE_SCALE,SCORE_REFERENCE_PLANE,featureProject,finalScorePosition,finalScoreIntersections,morphSample,exactStage,type SpaceStage} from '../../../lib/learning/nonlinear-space';
import {formatClassifierNumber as fmt} from '../../../lib/learning/classifier-lesson';
import {NonlinearThreeView} from './three-view';
import {useSpaceMorph} from './use-space-morph';
import {InputClassificationMap,ReluFunction,SmallNetwork} from './nonlinear-linked-views';
import s from './classifier-lesson.module.css';
import {valueColor} from '../../../lib/design/value-color';
import {ValueLegend} from './value-legend';
const STAGES=['一个线性分数','只做乘法与加法','加入 ReLU'] as const;
export function ScorePreview({position,selected}:{position:number;selected:string}){
 const path=(positions:readonly (readonly number[])[])=>positions.map(([x,y,z],i)=>{const p=featureProject(x,y,z);return `${i?'L':'M'}${p.x},${p.y}`;}).join(' '),pixelShape=[[-3,-7],[3,-7],[3,-5],[5,-5],[5,-3],[7,-3],[7,3],[5,3],[5,5],[3,5],[3,7],[-3,7],[-3,5],[-5,5],[-5,3],[-7,3],[-7,-3],[-5,-3],[-5,-5],[-3,-5]],scale=400/(2*FEATURE_HALF_WIDTH),point=CORNERS.find(p=>p.id===selected)!,top=finalScorePosition(point.x,point.y,position);
 return <svg viewBox="0 0 400 308" aria-hidden="true">{Array.from({length:25},(_,i)=>Array.from({length:25},(_,j)=>{const p=featureProject(...finalScorePosition(i/24,j/24,position));return <rect key={`${i}:${j}`} x={p.x-1} y={p.y-1} width="2" height="2" fill={valueColor(morphSample(i/24,j/24,position).score)}/>;}))}{[0,.25,.5,.75,1].flatMap(n=>[Array.from({length:25},(_,i)=>finalScorePosition(n,i/24,position)),Array.from({length:25},(_,i)=>finalScorePosition(i/24,n,position))]).map((line,i)=><path key={i} d={path(line)} fill="none" stroke="#6f6f66" strokeWidth=".7"/>)}<path d={path(SCORE_REFERENCE_PLANE)+'Z'} stroke="#d0d0bf" strokeWidth="1.5" fill="#d0d0bf" fillOpacity=".16"/>{finalScoreIntersections(position).map((line,i)=>{const p=featureProject(...line[0]);return Math.hypot(...line[0].map((v,j)=>v-line[1][j]))<1e-8?<circle key={i} cx={p.x} cy={p.y} r="3" fill="#fff"/>:<path key={i} d={path(line)} stroke="#fff" strokeWidth="2.4" fill="none"/>;})}<path d={path([[0,0,-1],[0,0,1.15]])} stroke="#999992"/>{[-2,0,2].map(n=>{const p=featureProject(0,0,n*FINAL_SCORE_SCALE);return <g key={n}><path d={`M${p.x-3},${p.y}h6`} stroke="#bcbcb5"/><text x={p.x-8} y={p.y+4} textAnchor="end" fill="#bcbcb5" fontSize="12">{n}</text></g>;})}{CORNERS.map(p=>{const v=morphSample(p.x,p.y,position),q=featureProject(p.x,p.y,0);return <g key={p.id}><rect x={q.x-.08*scale} y={q.y-.08*scale} width={.16*scale} height={.16*scale} fill="#151515"/>{p.label===0?<path d={`M${q.x-.051*scale},${q.y-.051*scale}h${.102*scale}v${.102*scale}h${-.102*scale}Z M${q.x-.033*scale},${q.y-.033*scale}v${.066*scale}h${.066*scale}v${-.066*scale}Z`} fill="#b0b0a9" fillRule="evenodd"/>:<path transform={`translate(${q.x},${q.y}) scale(${scale/120})`} d={pixelShape.map(([x,y],i)=>`${i?'L':'M'}${x},${y}`).join(' ')+'Z'} fill="#f0f0e9"/>}{v.predicted!==p.label&&<rect x={q.x-.085*scale} y={q.y-.085*scale} width={.17*scale} height={.17*scale} fill="none" stroke="#bcbcb5" strokeDasharray="2 2"/>}{p.id===selected&&<path d={`M${q.x-.1*scale},${q.y-.06*scale}v${-.04*scale}h${.04*scale}M${q.x+.1*scale},${q.y+.06*scale}v${.04*scale}h${-.04*scale}`} fill="none" stroke="#fff" strokeWidth="2"/>}</g>;})}{Math.abs(morphSample(point.x,point.y,position).score)>1e-12&&<><path d={path([[point.x,point.y,0],top])} stroke="#fff" strokeWidth="1.7" strokeDasharray="4 3" fill="none"/><circle cx={featureProject(...top).x} cy={featureProject(...top).y} r="3.4" fill="#fff"/></>}{[[1.16,0,0,'x₁'],[0,1.16,0,'x₂'],[0,0,1.2,'分数 s']].map(([x,y,z,label])=>{const p=featureProject(Number(x),Number(y),Number(z));return <text key={label} x={p.x} y={p.y} fill="#bcbcb5" fontSize="12">{label}</text>;})}</svg>;
}
export default function NonlinearSpace(){
 const rootRef=useRef<HTMLElement>(null),motion=useSpaceMorph(rootRef),position=motion.position,stage=exactStage(position),[selected,setSelected]=useState('00'),[view,setView]=useState<'space'|'map'>('space'),point=CORNERS.find(p=>p.id===selected)!,value=morphSample(point.x,point.y,position),count=CORNERS.filter(p=>morphSample(p.x,p.y,position).predicted===p.label).length,a=[point.x,point.y,point.x+point.y-1],t=position<=1?position:position-1;
 const status=stage===null?(position<1?'两个线性规则间的显示过渡':'加入 ReLU 的显示过渡'):STAGES[stage];
 return <section ref={rootRef} id="nonlinear-space" className={s.lesson} data-nonlinear-space aria-labelledby="nonlinear-title">
  <header className={s.heading}><span>03 / 为什么需要非线性</span><h2 id="nonlinear-title">ReLU 改变计算，分数面随之改变。</h2><p>继续把原始输入放在固定的 (x₁,x₂) 坐标上。每个位置经过当前网络算出最终分数 s，再按高度 z=s 作图。灰色零面同时是输入坐标面和 z=0（也就是 s=0）的判决参考面，原始样本始终留在上面。</p><p>隐藏层先产生新特征，再由输出单元把它们组合成 s。主图的第三轴一直是最终分数，隐藏特征值在旁边的网络图中逐项查看；ReLU 输出非负，也不意味着最后的 s 非负。</p></header>
  <p className={s.prompt}>先看“只做乘法与加法”，再点“加入 ReLU”。观察最终分数面怎样从平面变成带棱线的曲面，以及选中点的分数怎样穿过固定的零面。</p>
  <div className={s.experiment}>
   <div className={s.plotColumn}>
    <label className={s.sampleSelect}><span>跟着同一个点</span><select aria-label="选择空间变换中的样本" value={selected} onChange={e=>{motion.pause();setSelected(e.target.value);}}>{CORNERS.map(p=><option key={p.id} value={p.id}>({p.x}, {p.y}) · 真实类别 {p.label}</option>)}</select></label>
    <div className={s.caseControls} role="group" aria-label="选择相同计算的表示"><button aria-pressed={view==='space'} onClick={()=>setView('space')}>3D 分数面</button><button aria-pressed={view==='map'} onClick={()=>setView('map')}>2D 输入分类图</button></div>
    <div className={s.plotHeading}><span>{status}</span><strong>{count} / 4<small>{stage===null?' 过渡示意分类':' 当前分对'}</small></strong></div>
    <div hidden={view!=='space'} className={s.plot} role="group" aria-label={`${status}，原始输入 (${point.x},${point.y})，最终分数 ${fmt(value.score)}。`}><NonlinearThreeView stage={position} selected={selected} onInteract={motion.pause} fallback={<ScorePreview position={position} selected={selected}/>}/></div>
    <div hidden={view!=='map'} className={s.mapFrame}><InputClassificationMap position={position} selected={selected}/></div>
    <div className={s.stageChoice} role="group" aria-label="播放到计算阶段">{STAGES.map((title,i)=><button key={title} aria-pressed={stage===i} onClick={()=>motion.go(i as SpaceStage)}><span>0{i+1}</span>{title}</button>)}</div>
    <div className={s.motionControls}><button onClick={motion.play}>{motion.playing?'暂停':motion.reduced?(position===2?'回到仿射阶段':'下一步'):position===2?'重看 ReLU 折叠':'播放 / 继续'}</button><label>变换进度 <input aria-label="拖动空间变换进度，手动操作会暂停" type="range" min="0" max="2" step=".01" value={position} onChange={e=>motion.scrub(Number(e.target.value))}/></label></div>
    <p className={s.localResult}><b style={{color:valueColor(value.score)}}>s = {fmt(value.score)}</b><span>原始输入 ({point.x}, {point.y}) · 预测 {value.predicted} · 真实 {point.label}</span></p>
    <p className={s.signReading}>{stage===null?`当前先取显示插值特征 q (${Math.round(t*100)}%)，再算最终 s，曲面高度与预测均来自这个 s。这是教学过渡，不是训练。`:stage===0?'当前 s=x₁+x₂−0.5，是一张平面，四点分对 3 个。':stage===1?'只做乘法与加法时，s=1.5−x₁−x₂，仍是一张平面，四点分对 3 个。':'加入 ReLU 后，最终 s 的计算分成两段，形成带棱线的分数面；四角点全部分对。'}</p>
    <ValueLegend value={value.score}/><p className={s.legend}><span>空心方点：真实类别 0；实心像素点：真实类别 1。它们都留在灰色零面上。</span><span>数值颜色沿同一标尺连续变化：负蓝紫，零处低亮中性，正绿黄红。白色交线为 s=0，按原约定判为 1。</span><span>竖虚线连接选中的原始样本与单独的白色分数标记；不是把原始样本搬离坐标面。</span></p>
    <p className={s.note}>这里只有两张几何面：固定的坐标/判决零面，与计算得到的分数面。分数轴固定标为 −2 到 2，不随动画自动缩放。完整 ReLU 的零分交线对应输入中的 x₁+x₂=0.5 和 1.5。</p>
   </div>
   <div className={s.calculation}><h3 className={s.calculationTitle}>同一个点 ({point.x}, {point.y})，连起公式与图像</h3>
    <SmallNetwork position={position} x={point.x} y={point.y}/>
    <div className={s.formula}><span>{stage===0?'当前线性规则':'第三个隐藏单元：先算特征，再算最终分数'}</span><p>a₃ = {point.x} + {point.y} − 1 = {a[2]}</p><p>{stage===null?position<1?`显示值 = ${fmt(t)} × (${a[2]}) = ${fmt(value.h[2])}`:`显示值 = (1−${fmt(t)})×(${a[2]}) + ${fmt(t)}×max(0,${a[2]}) = ${fmt(value.h[2])}`:stage===2?`h₃ = max(0, ${a[2]}) = ${value.h[2]}`:stage===1?`直接传递 a₃ = ${a[2]}`:'当前尚未使用第三个隐藏单元，直接算 x₁+x₂−0.5'}</p><p>s = {fmt(value.h[0])} + {fmt(value.h[1])} − 2×({fmt(value.h[2])}) − 0.5 = <b>{fmt(value.score)}</b></p></div>
    <ReluFunction position={position} x={point.x} y={point.y}/><p>小函数图画的是隐藏单元 a₃→h₃；上面主图画的是输出层组合后的最终 s。两个纵轴的含义不同。</p>
   </div>
  </div>
  <div className={s.insight}><h3>谁决定分数面在哪里弯？</h3><p>权重和偏置先决定 a₃=x₁+x₂−1。ReLU 把这个隐藏单元的负值截为 0，然后输出层再算 s=x₁+x₂−2h₃−0.5。改变的是完整计算规则，所以最终分数面随之弯折；灰色 s=0 判决参考面一直不动。</p><p>只给一个单元加 ReLU 也不是这个 XOR 问题的解法：max(0,x₁+x₂−1) 把 (0,0)、(1,0)、(0,1) 都变成 0，不同类别的信息重合了。这里结合多个隐藏特征与非线性，再由输出单元组合它们；ReLU 只是非线性激活的一种选择。</p><p>只做乘法与加法时，把 a₃=x₁+x₂−1 代回输出，会得到 s=1.5−x₁−x₂，仍然是线性规则。加入 ReLU 后：x₁+x₂≤1 时，s=x₁+x₂−0.5；x₁+x₂≥1 时，s=1.5−x₁−x₂。两个分段在同一条棱线上接起来。ReLU 本身只处理隐藏值，最后的分数仍可为负。</p></div>
  <div className={s.limit}><h3>3 个隐藏单元，是这个例子的选择。</h3><p>之前是“2 个输入，1 个分类单元”。这里是“2 个输入，3 个隐藏单元，再加 1 个分类单元”，共 4 个计算单元。三个隐藏单元提供这个手工示例的三个特征，并不是为了凑主图的三个坐标轴；主图始终用两个原始输入加一个最终分数。它也不是 XOR 必须的最小结构。更一般地，XOR 需要非线性计算或非线性特征，并不必然需要名为“隐藏层”的结构；例如手工加入乘积特征 x₁x₂，再用 s=x₁+x₂−2x₁x₂−0.5，也能分开四角点。这已经改变了原始输入表示，不是仅靠原始两个输入的单层感知机。</p><p>这些权重是手工选的，没有训练。4/4 只针对四角点：例如 (0.4,0.4) 得到 s=0.3、预测 1；若把 XOR 扩展为以 x₁=0.5、x₂=0.5 划分的连续区域，这一点应该为 0，仍会分错。</p><p className={s.nextQuestion}>接下来才是：怎样让误差决定这些权重，而不用人手工选择？</p><p className={s.source}>参考：<a href="https://d2l.ai/chapter_multilayer-perceptrons/mlp.html" target="_blank" rel="noreferrer">隐藏层与 ReLU</a>。</p></div>
 </section>;
}
