"use client";
import {useEffect,useLayoutEffect,useMemo,useRef} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {AsciiRenderer,Billboard,Line,OrthographicCamera} from '@react-three/drei';
import * as THREE from 'three';
import {configureClassifierCamera,configureHeroCamera,createFoldGeometry} from '../../../lib/learning/three-opening-geometry';
import {SCORE_SCALE,SCORE_HALF_WIDTH,scorePosition,scorePlaneTriangles} from '../../../lib/learning/score-plane';
import {CORNERS,FEATURE_HALF_WIDTH,morphSample,FINAL_SCORE_SCALE,SCORE_REFERENCE_PLANE,finalScorePosition,finalScoreSurface,finalScoreIntersections} from '../../../lib/learning/nonlinear-space';
import {CameraInteraction,SceneLabel,type Interaction} from './three-camera-interaction';
import {foldHeight} from '../../../lib/learning/ascii-fold';
import {boundaryFor,boundarySegment,caseData,classify,type Camera,type CaseId,type Boundary} from '../../../lib/learning/opening-demo';

import {material} from '../../../lib/design/tokens';
import {valueColor} from '../../../lib/design/value-color';

type Lifecycle={onReady:()=>void;onFailure:(reason?:string)=>void;interaction?:Interaction};

function RuntimeGuard({onReady,onFailure}:Lifecycle){
 const {gl,invalidate,size}=useThree(),reported=useRef(false),alive=useRef(true);
 useEffect(()=>{alive.current=true;const canvas=gl.domElement;const lost=(event:Event)=>{event.preventDefault();onFailure('WebGL 上下文在运行时丢失。可尝试重新载入此场景。');};canvas.addEventListener('webglcontextlost',lost);const frame=requestAnimationFrame(()=>{canvas.parentElement?.querySelector('table')?.setAttribute('aria-hidden','true');invalidate();});return()=>{alive.current=false;cancelAnimationFrame(frame);canvas.removeEventListener('webglcontextlost',lost);};},[gl,invalidate,onFailure,size.width,size.height]);
 useFrame(()=>{if(!reported.current){reported.current=true;queueMicrotask(()=>{if(alive.current)onReady();});}});
 return null;
}
function HeroCamera(){const ref=useRef<THREE.OrthographicCamera>(null);const invalidate=useThree(s=>s.invalidate);useLayoutEffect(()=>{if(ref.current){configureHeroCamera(ref.current);invalidate();}},[invalidate]);return <OrthographicCamera ref={ref} makeDefault manual left={952/(2*Math.hypot(220,220))} right={-952/(2*Math.hypot(220,220))} top={790/(2*Math.hypot(116,116,301))} bottom={-790/(2*Math.hypot(116,116,301))} near={.1} far={30}/>;}
function ClassifierCamera({view}:{view:Camera}){const ref=useRef<THREE.OrthographicCamera>(null);const invalidate=useThree(s=>s.invalidate),yaw=view.yaw,tilt=view.tilt;useLayoutEffect(()=>{if(ref.current){configureClassifierCamera(ref.current,{yaw,tilt});invalidate();}},[yaw,tilt,invalidate]);return <OrthographicCamera ref={ref} makeDefault manual left={-400/240} right={400/240} top={308/240} bottom={-308/240} near={.1} far={20}/>;}
function FoldMesh(){
 const geometry=useMemo(()=>createFoldGeometry(),[]);useEffect(()=>()=>geometry.dispose(),[geometry]);
 const paths=useMemo(()=>[[-1,-1,-1,1],[1,-1,1,1],[0,-1,0,0],[0,0,1,-1]].map(([a,b,c,d])=>Array.from({length:80},(_,i)=>{const t=i/79,u=a+(c-a)*t,v=b+(d-b)*t;return [u,v,foldHeight(u,v)+.003] as [number,number,number];})),[]);
 return <><mesh geometry={geometry}><meshBasicMaterial vertexColors side={THREE.DoubleSide} toneMapped={false}/></mesh>{paths.map((points,i)=><Line key={i} points={points} color="#d0d0c7" lineWidth={1.25}/>)}</>;
}
function HeroAscii(){
 const {size,gl,invalidate}=useThree(),resolution=Math.min(.2,Math.max(.075,(size.width<600?60:100)/size.width));
 useEffect(()=>{let disposed=false;const align=()=>{if(disposed)return;const table=gl.domElement.parentElement?.querySelector('table');if(!table)return;const context=document.createElement('canvas').getContext('2d');if(!context)return;context.font='100px "Geist Mono", monospace';const advance=context.measureText('M').width/100,columns=Math.max(1,Math.floor(size.width*resolution)),rows=Math.max(1,Math.ceil(Math.floor(size.height*resolution)/2));table.style.fontFamily='"Geist Mono", monospace';table.style.fontSize=`${size.width/columns/advance}px`;table.style.letterSpacing='0px';table.style.lineHeight=`${size.height/rows}px`;table.setAttribute('aria-hidden','true');invalidate();};const frame=requestAnimationFrame(align);document.fonts?.ready.then(align);return()=>{disposed=true;cancelAnimationFrame(frame);};},[size.width,size.height,resolution,gl,invalidate]);
 return <AsciiRenderer characters=" .:;=+*#%@" fgColor={material.ink} bgColor={material.background} invert color={false} resolution={resolution}/>;
}
export function HeroScene(props:Lifecycle){return <Canvas frameloop="demand" dpr={1} flat gl={{antialias:false,alpha:false,powerPreference:'low-power'}} style={{touchAction:'pan-y'}} fallback={<span>浏览器不支持 canvas。当前显示二维预览。</span>} ><color attach="background" args={['#000000']}/><HeroCamera/><FoldMesh/>{props.interaction&&<CameraInteraction {...props.interaction} target={[0,0,(500-790/2)/301]}/>}<RuntimeGuard {...props}/><HeroAscii/></Canvas>;}

function usePlaneTexture({a,b,c}:Boundary){
 const texture=useMemo(()=>{const line={a,b,c};const canvas=document.createElement('canvas');canvas.width=canvas.height=768;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('2D texture context unavailable');ctx.fillStyle='#151515';ctx.fillRect(0,0,768,768);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='15px monospace';for(let row=0;row<31;row++)for(let col=0;col<41;col++){const x=-1+(col+.5)*2/41,y=1-(row+.5)*2/31,prediction=classify({x,y},line);ctx.fillStyle=prediction===1?'#96968d':'#595954';ctx.fillText(prediction===1?'+':':',(col+.5)*768/41,(row+.5)*768/31);}const map=new THREE.CanvasTexture(canvas);map.colorSpace=THREE.SRGBColorSpace;map.magFilter=THREE.NearestFilter;map.minFilter=THREE.LinearFilter;map.generateMipmaps=false;return map;},[a,b,c]);
 useEffect(()=>()=>texture.dispose(),[texture]);return texture;
}
function Sample({point,wrong,opacity,position}:{point:{x:number;y:number;label:0|1};wrong:boolean;opacity:number;position?:[number,number,number]}){
 const geometry=useMemo(()=>{const shape=new THREE.Shape();if(point.label===0){shape.moveTo(-.051,-.051);shape.lineTo(.051,-.051);shape.lineTo(.051,.051);shape.lineTo(-.051,.051);shape.closePath();const hole=new THREE.Path();hole.moveTo(-.033,-.033);hole.lineTo(-.033,.033);hole.lineTo(.033,.033);hole.lineTo(.033,-.033);hole.closePath();shape.holes.push(hole);}else{const vertices=[[-3,-7],[3,-7],[3,-5],[5,-5],[5,-3],[7,-3],[7,3],[5,3],[5,5],[3,5],[3,7],[-3,7],[-3,5],[-5,5],[-5,3],[-7,3],[-7,-3],[-5,-3],[-5,-5],[-3,-5]];vertices.forEach(([x,y],i)=>{if(i===0)shape.moveTo(x/120,y/120);else shape.lineTo(x/120,y/120);});shape.closePath();}return new THREE.ShapeGeometry(shape);},[point.label]);
 useEffect(()=>()=>geometry.dispose(),[geometry]);
 return <Billboard position={position??[point.x,point.y,.015]}><mesh position={[0,0,-.002]}><planeGeometry args={[.16,.16]}/><meshBasicMaterial color={material.background} transparent opacity={opacity} depthTest={false}/></mesh><mesh geometry={geometry} renderOrder={2}><meshBasicMaterial color={point.label===0?material.class0:material.class1} side={THREE.DoubleSide} transparent opacity={opacity} depthTest={false}/></mesh>{wrong&&<Line points={[[-.085,-.085,0],[-.085,.085,0],[.085,.085,0],[.085,-.085,0],[-.085,-.085,0]]} color={material.secondary} lineWidth={1} dashed dashSize={.018} gapSize={.018} transparent opacity={opacity} depthTest={false}/>}</Billboard>;
}
function ClassificationObjects({id,proof,opacity,line,selected,mapOpacity=1}:{id:CaseId;proof:boolean;opacity:number;line?:Boundary;selected?:string;mapOpacity?:number}){
 const boundary=line??boundaryFor(id),texture=usePlaneTexture(boundary),points=caseData(id),segment=(Math.hypot(boundary.a,boundary.b)>1e-9?boundarySegment(boundary):[]).map(p=>[p.x,p.y,.012] as [number,number,number]);
 const grid=useMemo(()=>{const vertices:number[]=[];for(const n of [-1,-.75,-.5,-.25,0,.25,.5,.75,1])vertices.push(n,-1,.004,n,1,.004,-1,n,.004,1,n,.004);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));return geometry;},[]);useEffect(()=>()=>grid.dispose(),[grid]);
 return <><mesh><planeGeometry args={[2,2]}/><meshBasicMaterial map={texture} side={THREE.DoubleSide} toneMapped={false} transparent={mapOpacity<1} opacity={mapOpacity} depthWrite={mapOpacity===1}/></mesh><lineSegments geometry={grid}><lineBasicMaterial color="#41413d"/></lineSegments>{segment.length>=2&&<Line points={segment} color={material.ink} lineWidth={1.6}/>}{points.map(point=><Sample key={point.id} point={point} wrong={classify(point,boundary)!==point.label} opacity={opacity}/>)}{selected&&points.filter(p=>p.id===selected).map(p=><Billboard key={'selected-'+p.id} position={[p.x,p.y,.02]}><Line points={[[-.11,-.07,0],[-.11,-.11,0],[-.07,-.11,0]]} color={material.highlight} lineWidth={2} depthTest={false}/><Line points={[[.11,.07,0],[.11,.11,0],[.07,.11,0]]} color={material.highlight} lineWidth={2} depthTest={false}/></Billboard>)}{id==='xor'&&proof&&[[points[0],points[1]],[points[2],points[3]]].map((pair,i)=><Line key={i} points={pair.map(p=>[p.x,p.y,.009] as [number,number,number])} color={material.wire} dashed dashSize={.035} gapSize={.045} lineWidth={1}/>)}</>;
}
export function ClassificationScene({view,id,proof,opacity,line,selected,...lifecycle}:Lifecycle&{view:Camera;id:CaseId;proof:boolean;opacity:number;line?:Boundary;selected?:string}){return <Canvas frameloop="demand" dpr={[1,1.5]} flat gl={{antialias:false,alpha:false,powerPreference:'low-power'}} style={{touchAction:'pan-y'}} fallback={<span>浏览器不支持 canvas。当前显示二维预览。</span>} ><color attach="background" args={[material.background]}/><ClassifierCamera view={view}/><ClassificationObjects id={id} proof={proof} opacity={opacity} line={line} selected={selected}/><SceneLabel position={[1.15,0,0]}>x₁</SceneLabel><SceneLabel position={[0,1.15,0]}>x₂</SceneLabel>{lifecycle.interaction&&<CameraInteraction {...lifecycle.interaction} target={[0,0,0]} syncKey={`${view.yaw}:${view.tilt}`}/>}<RuntimeGuard {...lifecycle}/></Canvas>;}

function ScoreCamera(){const ref=useRef<THREE.OrthographicCamera>(null),invalidate=useThree(s=>s.invalidate);useLayoutEffect(()=>{if(!ref.current)return;ref.current.position.set(3,-4,3);ref.current.up.set(0,0,1);ref.current.lookAt(0,0,0);ref.current.updateMatrixWorld();invalidate();},[invalidate]);return <OrthographicCamera ref={ref} makeDefault manual left={-SCORE_HALF_WIDTH} right={SCORE_HALF_WIDTH} top={SCORE_HALF_WIDTH*308/400} bottom={-SCORE_HALF_WIDTH*308/400} near={.1} far={30}/>;}
function ScoreObjects({id,line,selected}:{id:CaseId;line:Boundary;selected?:string}){
 const {a,b,c}=line,geometry=useMemo(()=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(scorePlaneTriangles({a,b,c}),3));g.computeVertexNormals();return g;},[a,b,c]);useEffect(()=>()=>geometry.dispose(),[geometry]);
 const point=caseData(id).find(p=>p.id===selected),wire=useMemo(()=>[-1,-.5,0,.5,1].flatMap(n=>[[scorePosition(n,-1,{a,b,c}),scorePosition(n,1,{a,b,c})],[scorePosition(-1,n,{a,b,c}),scorePosition(1,n,{a,b,c})]]),[a,b,c]);
 const coincident=a===0&&b===0&&c===0;
 return <><ClassificationObjects id={id} proof={false} opacity={1} line={line} selected={selected} mapOpacity={.45}/>
  {!coincident&&<mesh geometry={geometry} renderOrder={1}><meshBasicMaterial color="#b8b8a9" transparent opacity={.22} side={THREE.DoubleSide} depthWrite={false}/></mesh>}
  {!coincident&&wire.map((points,i)=><Line key={i} points={points} color={material.secondary} lineWidth={i===4||i===5?1.3:.8} transparent opacity={.85}/>)}
  <Line points={[[-1,-1,0],[1,-1,0],[1,1,0],[-1,1,0],[-1,-1,0]]} color="#77776e" lineWidth={1}/>
  <Line points={[[-1.15,-1.15,-6*SCORE_SCALE],[-1.15,-1.15,6*SCORE_SCALE]]} color="#a0a098" lineWidth={1}/>
  {[-6,-3,0,3,6].map(z=><Line key={z} points={[[-1.19,-1.15,z*SCORE_SCALE],[-1.11,-1.15,z*SCORE_SCALE]]} color={material.secondary} lineWidth={1}/>)}
  {point&&<><Line points={[[point.x,point.y,0],scorePosition(point.x,point.y,line)]} color={material.highlight} lineWidth={1.7} dashed dashSize={.035} gapSize={.025} depthTest={false}/><mesh position={scorePosition(point.x,point.y,line)} renderOrder={3}><sphereGeometry args={[.036,8,6]}/><meshBasicMaterial color={material.highlight} depthTest={false}/></mesh></>}
 </>;
}
export function ScoreScene({id,line,selected,...lifecycle}:Lifecycle&{id:CaseId;line:Boundary;selected?:string}){return <Canvas frameloop="demand" dpr={[1,1.5]} flat gl={{antialias:false,alpha:false,powerPreference:'low-power'}} style={{touchAction:'pan-y'}} fallback={<span>浏览器不支持 canvas。当前显示二维预览。</span>}><color attach="background" args={[material.background]}/><ScoreCamera/><ScoreObjects id={id} line={line} selected={selected}/><SceneLabel position={[1.2,-1,0]}>x₁</SceneLabel><SceneLabel position={[-1,1.2,0]}>x₂</SceneLabel><SceneLabel position={[-1.15,-1.15,6.5*SCORE_SCALE]}>z 分数</SceneLabel>{[-6,-3,0,3,6].map(z=><SceneLabel key={z} position={[-1.3,-1.15,z*SCORE_SCALE]}>{z}</SceneLabel>)}{lifecycle.interaction&&<CameraInteraction {...lifecycle.interaction} target={[0,0,0]}/>}<RuntimeGuard {...lifecycle}/></Canvas>;}

function FeatureCamera(){const ref=useRef<THREE.OrthographicCamera>(null),invalidate=useThree(s=>s.invalidate);useLayoutEffect(()=>{if(!ref.current)return;ref.current.position.set(3.5,-3.5,3);ref.current.up.set(0,0,1);ref.current.lookAt(.5,.5,0);ref.current.updateMatrixWorld();invalidate();},[invalidate]);return <OrthographicCamera ref={ref} makeDefault manual left={-FEATURE_HALF_WIDTH} right={FEATURE_HALF_WIDTH} top={FEATURE_HALF_WIDTH*308/400} bottom={-FEATURE_HALF_WIDTH*308/400} near={.1} far={30}/>;}
function FeatureObjects({stage,selected}:{stage:number;selected:string}){
 const surface=useMemo(()=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(finalScoreSurface(0,24),3));g.setAttribute('color',new THREE.Float32BufferAttribute(new Float32Array(g.getAttribute('position').count*3),3));return g;},[]);
 useLayoutEffect(()=>{const attr=surface.getAttribute('position'),colors=surface.getAttribute('color');for(let i=0;i<attr.count;i++){const x=attr.getX(i),y=attr.getY(i),score=morphSample(x,y,stage).score;attr.setZ(i,score*FINAL_SCORE_SCALE);const color=new THREE.Color(valueColor(score));colors.setXYZ(i,color.r,color.g,color.b);}attr.needsUpdate=true;colors.needsUpdate=true;surface.computeBoundingSphere();},[surface,stage]);useEffect(()=>()=>surface.dispose(),[surface]);
 const plane=useMemo(()=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([0,1,2,0,2,3].flatMap(i=>SCORE_REFERENCE_PLANE[i]),3));return g;},[]);
 const pixels=useMemo(()=>{const vertices:number[]=[];for(let i=0;i<=24;i++)for(let j=0;j<=24;j++)vertices.push(...finalScorePosition(i/24,j/24,0));const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setAttribute('color',new THREE.Float32BufferAttribute(new Float32Array(vertices.length),3));return g;},[]);useLayoutEffect(()=>{const attr=pixels.getAttribute('position'),colors=pixels.getAttribute('color');for(let i=0;i<attr.count;i++){const score=morphSample(attr.getX(i),attr.getY(i),stage).score;attr.setZ(i,score*FINAL_SCORE_SCALE);const color=new THREE.Color(valueColor(score));colors.setXYZ(i,color.r,color.g,color.b);}attr.needsUpdate=true;colors.needsUpdate=true;pixels.computeBoundingSphere();},[pixels,stage]);
 useEffect(()=>()=>plane.dispose(),[plane]);useEffect(()=>()=>pixels.dispose(),[pixels]);
 const wire=[0,.25,.5,.75,1].flatMap(n=>[Array.from({length:25},(_,i)=>finalScorePosition(n,i/24,stage)),Array.from({length:25},(_,i)=>finalScorePosition(i/24,n,stage))]),point=CORNERS.find(p=>p.id===selected)!;
 return <><mesh geometry={surface}><meshBasicMaterial vertexColors transparent opacity={.12} side={THREE.DoubleSide} depthWrite={false}/></mesh><points geometry={pixels}><pointsMaterial vertexColors size={2} sizeAttenuation={false}/></points>{wire.map((points,i)=><Line key={i} points={points} color="#6f6f66" lineWidth={.7}/>)}
  <mesh geometry={plane} renderOrder={1}><meshBasicMaterial color="#d0d0bf" transparent opacity={.16} side={THREE.DoubleSide} depthWrite={false}/></mesh><Line points={[...SCORE_REFERENCE_PLANE,SCORE_REFERENCE_PLANE[0]]} color="#d0d0bf" lineWidth={1.5}/>
  {finalScoreIntersections(stage).map((segment,i)=>Math.hypot(...segment[0].map((n,k)=>n-segment[1][k]))>1e-8?<Line key={i} points={segment} color={material.highlight} lineWidth={2.4} depthTest={false}/>:<mesh key={i} position={segment[0]}><sphereGeometry args={[.025,8,6]}/><meshBasicMaterial color={material.highlight} depthTest={false}/></mesh>)}
  <SceneLabel position={[1.16,0,0]}>x₁</SceneLabel><SceneLabel position={[0,1.16,0]}>x₂</SceneLabel><SceneLabel position={[0,0,1.2]}>分数 s</SceneLabel>{[-2,0,2].map(s=><SceneLabel key={s} position={[-.1,0,s*FINAL_SCORE_SCALE]}>{s}</SceneLabel>)}
  <Line points={[[0,0,-1],[0,0,1.15]]} color={material.muted} lineWidth={1}/><Line points={[[0,0,0],[1.15,0,0]]} color={material.muted}/><Line points={[[0,0,0],[0,1.15,0]]} color={material.muted}/>
  {[-2,0,2].map(s=><Line key={s} points={[[-.025,0,s*FINAL_SCORE_SCALE],[.025,0,s*FINAL_SCORE_SCALE]]} color={material.secondary}/>)}
  {CORNERS.map(p=>{const v=morphSample(p.x,p.y,stage);return <group key={p.id}><Sample point={p} wrong={v.predicted!==p.label} opacity={1} position={[p.x,p.y,0]}/>{selected===p.id&&<Billboard position={[p.x,p.y,0]}><Line points={[[-.1,-.06,0],[-.1,-.1,0],[-.06,-.1,0]]} color={material.highlight} lineWidth={2} depthTest={false}/><Line points={[[.1,.06,0],[.1,.1,0],[.06,.1,0]]} color={material.highlight} lineWidth={2} depthTest={false}/></Billboard>}</group>;})}
  {Math.abs(morphSample(point.x,point.y,stage).score)>1e-12&&<><Line points={[[point.x,point.y,0],finalScorePosition(point.x,point.y,stage)]} color={material.highlight} lineWidth={1.7} dashed dashSize={.035} gapSize={.025} depthTest={false}/><mesh position={finalScorePosition(point.x,point.y,stage)} renderOrder={3}><sphereGeometry args={[.032,8,6]}/><meshBasicMaterial color={material.highlight} depthTest={false}/></mesh></>}
 </>;
}
export function NonlinearScene({stage,selected,...lifecycle}:Lifecycle&{stage:number;selected:string}){return <Canvas frameloop="demand" dpr={[1,1.5]} flat gl={{antialias:false,alpha:false,powerPreference:'low-power'}} style={{touchAction:'pan-y'}} fallback={<span>浏览器不支持 canvas。当前显示二维预览。</span>}><color attach="background" args={[material.background]}/><FeatureCamera/><FeatureObjects stage={stage} selected={selected}/>{lifecycle.interaction&&<CameraInteraction {...lifecycle.interaction} target={[.5,.5,0]}/>}<RuntimeGuard {...lifecycle}/></Canvas>;}
