import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {CORNERS,FEATURE_HALF_WIDTH,OUTPUT_PLANE,featureCoordinates,featureSample,featureCount,featureProject,featureSurface} from '../lib/learning/nonlinear-space.ts';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
test('three actual stages preserve labels, expose affine failure and then separate four corners',()=>{assert.deepEqual([0,1,2].map(featureCount),[3,3,4]);assert.deepEqual(featureCoordinates(0,0,1),[0,0,-1]);assert.deepEqual(featureCoordinates(0,0,2),[0,0,0]);assert.deepEqual(featureCoordinates(1,1,2),[1,1,1]);for(const p of CORNERS){close(featureSample(p.x,p.y,1).score,1.5-p.x-p.y);assert.equal(featureSample(p.x,p.y,2).predicted,p.label);}assert.equal(featureSample(.4,.4,2).predicted,1);});
test('every triangle is planar within one ReLU branch, including the exact crease',()=>{for(const stage of [0,1,2]){const vertices=featureSurface(stage);for(let i=0;i<vertices.length;i+=9){const p=[vertices.slice(i,i+3),vertices.slice(i+3,i+6),vertices.slice(i+6,i+9)],x=p.reduce((s,q)=>s+q[0],0)/3,y=p.reduce((s,q)=>s+q[1],0)/3,z=p.reduce((s,q)=>s+q[2],0)/3;close(z,featureCoordinates(x,y,stage)[2]);}}});
test('output plane is the same zero-score plane in affine and activated feature coordinates',()=>{for(const [x,y,z]of OUTPUT_PLANE)close(x+y-2*z-.5,0);});
test('feature camera labels match actual Three projection with fixed axes through all stages',()=>{const cam=new THREE.OrthographicCamera(-FEATURE_HALF_WIDTH,FEATURE_HALF_WIDTH,FEATURE_HALF_WIDTH*308/400,-FEATURE_HALF_WIDTH*308/400,.1,30);cam.position.set(3.5,-3.5,3);cam.up.set(0,0,1);cam.lookAt(.5,.5,0);cam.updateMatrixWorld();for(const stage of [0,1,2])for(const p of CORNERS){const h=featureCoordinates(p.x,p.y,stage),v=new THREE.Vector3(...h).project(cam),q=featureProject(...h);close((v.x+1)*200,q.x);close((1-v.y)*154,q.y);assert.ok(q.x>0&&q.x<400&&q.y>0&&q.y<308);}});

import {morphCoordinates,morphSample,morphIntersections,morphSurface,exactStage} from '../lib/learning/nonlinear-space.ts';
import {readFile} from 'node:fs/promises';
test('continuous morph preserves every endpoint and positive ReLU branch while lifting only negative values',()=>{for(const p of CORNERS){for(const stage of [0,1,2])assert.deepEqual(morphCoordinates(p.x,p.y,stage),featureCoordinates(p.x,p.y,stage));for(let t=0;t<=1;t+=.05){const a=p.x+p.y-1,h=morphCoordinates(p.x,p.y,1+t);close(h[2],a+t*(Math.max(0,a)-a));if(a>=0)close(h[2],a);}}});
test('all intermediate intersections lie on both surfaces, including root birth and degenerate moments',()=>{for(let i=0;i<=200;i++){const position=i/100;for(const line of morphIntersections(position))for(const [x,y,z]of line){assert.ok(x>=-1e-9&&x<=1+1e-9&&y>=-1e-9&&y<=1+1e-9);close(morphSample(x,y,position).score,0);close(z,morphCoordinates(x,y,position)[2]);close(x+y-2*z-.5,0);}}assert.equal(morphIntersections(.5).length,0);assert.equal(morphIntersections(1.5).length,1);assert.equal(morphIntersections(2).length,2);assert.deepEqual(morphIntersections(1.75)[0],[[0,0,-.25],[0,0,-.25]]);});
test('current classification is explicitly available for intermediate geometry, not substituted endpoint data',()=>{assert.equal(CORNERS.filter(p=>morphSample(p.x,p.y,.5).predicted===p.label).length,2);assert.equal(morphSample(0,0,1.75).predicted,1);assert.equal(morphSample(0,0,1.76).predicted,0);assert.equal(exactStage(1.5),null);assert.equal(exactStage(2),2);for(let i=0;i<=20;i++){const p=i/10,v=morphSurface(p);for(let j=0;j<v.length;j+=9){const x=(v[j]+v[j+3]+v[j+6])/3,y=(v[j+1]+v[j+4]+v[j+7])/3,z=(v[j+2]+v[j+5]+v[j+8])/3;close(z,morphCoordinates(x,y,p)[2]);}}});
test('Canvas fallback is pure content, never an unconditional failure effect',async()=>{const source=await readFile('app/learn/neural-networks/three-opening-scenes.tsx','utf8');assert.doesNotMatch(source,/CanvasUnavailable/);assert.equal((source.match(/fallback=\{<span>/g)||[]).length,4);assert.match(source,/webglcontextlost/);const host=await readFile('app/learn/neural-networks/three-view.tsx','utf8');assert.match(host,/componentDidCatch\(error:Error\)/);assert.match(host,/error\.message/);assert.match(host,/重试三维/);});
test('camera interaction owns real controls, tracks labels, cleans gestures and supports keyboard alternatives',async()=>{const source=await readFile('app/learn/neural-networks/three-camera-interaction.tsx','utf8'),host=await readFile('app/learn/neural-networks/three-view.tsx','utf8');assert.match(source,/<CameraControls/);assert.match(source,/updateCameraUp/);assert.match(source,/TOUCH_ZOOM/);assert.match(source,/<Html/);assert.match(host,/ArrowLeft:'left'/);assert.match(host,/onPointerDown=\{e=>e.stopPropagation\(\)\}/);});

import {FINAL_SCORE_SCALE,SCORE_REFERENCE_PLANE,finalScorePosition,finalScoreRegions,finalScoreIntersections} from '../lib/learning/nonlinear-space.ts';
test('main nonlinear view keeps the input reference at zero and plots the actual final score',()=>{assert.deepEqual(SCORE_REFERENCE_PLANE,[[0,0,0],[1,0,0],[1,1,0],[0,1,0]]);for(let step=0;step<=80;step++){const p=step/40;for(const sample of CORNERS){const v=finalScorePosition(sample.x,sample.y,p);assert.deepEqual(v.slice(0,2),[sample.x,sample.y]);close(v[2]/FINAL_SCORE_SCALE,morphSample(sample.x,sample.y,p).score);}}close(morphSample(0,0,.5).score,.5);close(finalScorePosition(0,0,1)[2]/FINAL_SCORE_SCALE,1.5);close(finalScorePosition(0,0,2)[2]/FINAL_SCORE_SCALE,-.5);});
test('colored score triangles partition the input square and agree with current interpolated scores',()=>{for(let step=0;step<=80;step++){const p=step/40;let area=0;for(const region of finalScoreRegions(p)){assert.ok(region.vertices.length<=18);for(let i=0;i<region.vertices.length;i+=9){const a=region.vertices.slice(i,i+3),b=region.vertices.slice(i+3,i+6),c=region.vertices.slice(i+6,i+9),x=(a[0]+b[0]+c[0])/3,y=(a[1]+b[1]+c[1])/3,z=(a[2]+b[2]+c[2])/3,score=morphSample(x,y,p).score;close(z/FINAL_SCORE_SCALE,score);assert.ok(score*(region.positive?1:-1)>=-1e-10);area+=Math.abs((b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]))/2;}}close(area,1);}});
test('score zero contours lie on both the final score surface and the fixed coordinate plane',()=>{for(let step=0;step<=160;step++)for(const line of finalScoreIntersections(step/80))for(const [x,y,z]of line){assert.equal(z,0);close(morphSample(x,y,step/80).score,0);}assert.equal(finalScoreIntersections(.5).length,0);assert.equal(finalScoreIntersections(2).length,2);});
