import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';
const{default:worker}=await import('../dist/server/index.js');
async function html(path){const response=await worker.fetch(new Request('http://localhost'+path,{headers:{accept:'text/html'}}),{ASSETS:{fetch:async()=>new Response('Not found',{status:404})}},{waitUntil(){},passThroughOnException(){}});assert.equal(response.status,200);return(await response.text()).replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<!--[\s\S]*?-->/g,'');}
test('canonical lesson contains the approved opening and its local neuron continuation',async()=>{const text=await html('/learn/neural-networks');assert.match(text,/data-opening-prototype/);assert.match(text,/先看分类/);assert.match(text,/第一组/);assert.match(text,/8 \/ 8/);assert.match(text,/类别 0/);assert.match(text,/类别 1/);assert.match(text,/加载三维场景/);assert.match(text,/重播/);assert.match(text,/转到斜视/);assert.equal((text.match(/data-ascii-fold=/g)||[]).length,2);assert.equal((text.match(/<svg\b/g)||[]).length,8);assert.match(text,/id="one-neuron"/);assert.match(text,/data-classifier-lesson/);assert.match(text,/同一次计算，写成公式/);assert.match(text,/3D 分数平面/);assert.match(text,/2D 分类图/);assert.match(text,/第三维是计算得到的分数/);assert.match(text,/看两侧为什么翻转/);assert.match(text,/id="nonlinear-space"/);assert.match(text,/加入 ReLU/);assert.match(text,/主图的第三轴一直是最终分数/);assert.match(text,/z=0（也就是 s=0）/);assert.match(text,/原始样本始终留在上面/);assert.match(text,/ReLU 函数/);assert.match(text,/变换进度/);assert.match(await readFile('app/learn/neural-networks/nonlinear-space.tsx','utf8'),/过渡示意分类/);assert.match(text,/2D 输入分类图/);assert.doesNotMatch(text,/data-linear-fit|data-hidden-space|data-foundations-article/);});
test('old full article is recoverable at a separate explicit archive route',async()=>{const text=await html('/learn/neural-networks/archive');assert.match(text,/data-foundations-article/);assert.match(text,/data-linear-fit/);});
test('demo has real pause, reduced motion, visibility pause, camera-only controls and no pinned scene',async()=>{const source=await readFile('app/learn/neural-networks/opening-demo.tsx','utf8'),css=await readFile('app/learn/neural-networks/opening-demo.module.css','utf8');assert.match(source,/prefers-reduced-motion/);assert.match(source,/visibilitychange/);assert.match(source,/cancelAnimationFrame/);assert.match(source,/IntersectionObserver/);assert.match(source,/这里明确换了数据/);assert.match(source,/后续用手工网络变换坐标，尚未训练网络/);assert.doesNotMatch(source,/scrollBy|scrollIntoView|onFocusCapture/);assert.doesNotMatch(css,/position:\s*(?:fixed|sticky)/);assert.match(css,/touch-action:pan-y/);});

test('Three, Fiber and Drei are the primary lazy renderer with explicit fallback and bounded lifecycles',async()=>{
 const scene=await readFile('app/learn/neural-networks/three-opening-scenes.tsx','utf8'),host=await readFile('app/learn/neural-networks/three-view.tsx','utf8'),opening=await readFile('app/learn/neural-networks/opening-demo.tsx','utf8');
 assert.match(scene,/from '@react-three\/fiber'/);assert.match(scene,/from '@react-three\/drei'/);assert.match(scene,/<AsciiRenderer/);assert.match(scene,/<mesh geometry=/);assert.match(scene,/frameloop="demand"/);assert.match(scene,/dpr=\{\[1,1\.5\]\}/);assert.match(scene,/webglcontextlost/);assert.match(scene,/geometry\.dispose/);assert.match(scene,/texture\.dispose/);
 assert.match(host,/lazy\(\(\)=>import/);assert.match(host,/三维场景未能启动/);assert.match(host,/不是实时三维渲染/);assert.match(opening,/rendererStatus\.current==='webgl'/);assert.match(opening,/rendererMode==='loading'/);
 const text=await html('/learn/neural-networks');assert.match(text,/data-three-renderer="loading"/);assert.match(text,/当前为二维预览/);
});
