import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {SCORE_SCALE,SCORE_HALF_WIDTH,scorePosition,scoreProject,scorePlaneRelation,scorePlaneTriangles} from '../lib/learning/score-plane.ts';
import {classifierScore,classify,boundarySegment,caseData} from '../lib/learning/opening-demo.ts';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
test('score-plane vertices are the same classifier scores, with a fixed declared scale',()=>{for(const a of [-2,0,2])for(const b of [-2,0,2])for(const c of [-2,0,2]){const line={a,b,c},vertices=scorePlaneTriangles(line);assert.equal(vertices.length,18);for(let i=0;i<vertices.length;i+=3)close(vertices[i+2],classifierScore({x:vertices[i],y:vertices[i+1]},line)*SCORE_SCALE);for(const p of caseData('xor'))close(scorePosition(p.x,p.y,line)[2],classifierScore(p,line)*SCORE_SCALE);}});
test('score camera and HTML/fallback labels agree, and fixed camera contains control extrema',()=>{const camera=new THREE.OrthographicCamera(-SCORE_HALF_WIDTH,SCORE_HALF_WIDTH,SCORE_HALF_WIDTH*308/400,-SCORE_HALF_WIDTH*308/400,.1,30);camera.position.set(3,-4,3);camera.up.set(0,0,1);camera.lookAt(0,0,0);camera.updateMatrixWorld();for(const x of [-1,0,1])for(const y of [-1,0,1])for(const z of [-6,0,6]){const p=new THREE.Vector3(x,y,z*SCORE_SCALE).project(camera),q=scoreProject(x,y,z);close((p.x+1)*200,q.x);close((1-p.y)*154,q.y);assert.ok(q.x>0&&q.x<400&&q.y>0&&q.y<308);}});
test('intersection lies on both zero map and score plane; constants are parallel or coincident',()=>{for(const line of [{a:1,b:0,c:0},{a:1,b:1,c:.1},{a:-2,b:.5,c:.2}]){assert.equal(scorePlaneRelation(line),'crossing');for(const p of boundarySegment(line))close(classifierScore(p,line),0);}assert.equal(scorePlaneRelation({a:0,b:0,c:0}),'coincident');assert.equal(scorePlaneRelation({a:0,b:0,c:1}),'above');assert.equal(scorePlaneRelation({a:0,b:0,c:-1}),'below');assert.equal(scorePlaneRelation({a:.1,b:0,c:2}),'outside');});
test('positive-zero-negative weight reverses orientation, not the nonzero separator position',()=>{for(const p of caseData('xor')){assert.equal(classify(p,{a:1,b:0,c:0}),p.x>0?1:0);assert.equal(classify(p,{a:0,b:0,c:0}),1);assert.equal(classify(p,{a:-1,b:0,c:0}),p.x<0?1:0);}for(const a of [-1,1])for(const p of boundarySegment({a,b:0,c:0}))close(p.x,0);});
test('touching either corner is a single intersection point in the displayed map',()=>{for(const c of [-2,2]){const line={a:1,b:1,c};assert.equal(boundarySegment(line).length,1);assert.equal(scorePlaneRelation(line),'tangent');}});
