/** Single source for CSS, SVG and Canvas materials. Numeric colors are not class or status colors. */
export const material = {
  background: '#151515', surface: '#1d1d1c', raised: '#252524', elevated: '#30302e',
  ink: '#e8e8e2', secondary: '#bcbcb5', muted: '#999992', rule: '#454542',
  wire: '#8d8d84', grid: '#343432', highlight: '#ffffff',
  class0: '#b0b0a9', class1: '#f0f0e9', region0: '#1c1c1b', region1: '#242423',
} as const;

export const VALUE_COLOR_STOPS = [
  { value: -2, color: '#a58bf5' },
  { value: -1, color: '#6b9be8' },
  { value: 0, color: '#66665f' },
  { value: .5, color: '#7ecb91' },
  { value: 1.25, color: '#e2cc72' },
  { value: 2, color: '#ec806b' },
] as const;

export const foundation = {
  'bg': material.background, 'surface-1': material.surface, 'surface-2': material.raised,
  'surface-3': material.elevated, 'text-primary': material.ink,
  'text-secondary': material.secondary, 'text-muted': material.muted,
  'border-subtle': material.grid, 'border-default': material.rule, 'border-active': material.wire,
  'accent': material.ink, 'accent-soft': material.elevated,
  'control-fill': material.ink, 'control-hover': material.highlight, 'control-ink': material.background,
  'status-success': material.ink, 'status-success-soft': material.raised,
  'status-error': '#e4afa7', 'status-error-soft': '#332725',
  'status-warning': '#e2cc72', 'status-warning-soft': '#332e20',
  'radius-1': '0px', 'radius-2': '2px', 'radius-3': '2px', 'radius-4': '4px',
  'space-1': '.25rem', 'space-2': '.5rem', 'space-3': '.75rem', 'space-4': '1rem',
  'space-5': '1.5rem', 'space-6': '2rem', 'space-7': '3rem', 'space-8': '4rem',
  'space-9': '6rem', 'space-10': '8rem',
  'type-display': 'clamp(2.75rem, 5.5vw, 5rem)', 'type-h1': 'clamp(2.25rem, 4.4vw, 4rem)',
  'type-h2': 'clamp(1.875rem, 3.25vw, 2.875rem)', 'type-h3': 'clamp(1.5rem, 2.1vw, 1.875rem)',
  'type-large': 'clamp(1.0625rem, 1.5vw, 1.25rem)', 'type-body': '1rem',
  'type-label': '.875rem', 'type-caption': '.75rem',
  'font-geist-sans': '"MiSans", "Noto Sans SC", "Microsoft YaHei UI", "Microsoft YaHei", "PingFang SC", "Geist"',
  'font-geist-mono': '"Geist Mono", "Cascadia Mono", Consolas',
  'motion-fast': '150ms', 'motion-panel': '220ms', 'motion-entrance': '420ms',
  'ease': 'cubic-bezier(.2,.7,.2,1)',
  'shadow-button': 'none', 'shadow-surface': 'none', 'shadow-panel': '0 12px 32px rgb(0 0 0 / 36%)',
  'overlay-scrim': 'rgb(0 0 0 / 65%)',
  'opening-bg': material.background, 'opening-surface': material.surface, 'opening-ink': material.ink,
  'opening-secondary': material.secondary, 'opening-muted': material.muted,
  'opening-rule': material.rule, 'opening-wire': material.wire,
  'opening-class-0': material.class0, 'opening-class-1': material.class1,
  'opening-region-0': material.region0, 'opening-region-1': material.region1,
  'opening-space-1': '.5rem', 'opening-space-2': '1rem', 'opening-space-3': '1.5rem',
  'opening-space-4': '2.5rem', 'opening-space-5': '4rem',
  'opening-radius': '0px', 'opening-stroke': '1px', 'opening-control-height': '48px',
  'opening-mono': 'var(--font-geist-mono), monospace',
  'opening-body': '1rem', 'opening-label': '.875rem', 'opening-meta': '.75rem',
  'opening-heading': '3.375rem', 'opening-line-height': '1.8',
  'graph-stroke': '1px', 'graph-selection-stroke': '2px', 'graph-glyph-size': '8px',
  'graph-zero': VALUE_COLOR_STOPS[2].color,
} as const;
